# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='images')),
                ('short_description', models.CharField(max_length=150)),
                ('long_description', models.CharField(max_length=300)),
                ('scientific_name', models.CharField(max_length=150)),
                ('taxonomic_classification', models.CharField(max_length=150)),
            ],
        ),
    ]
