# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversidad_app', '0002_auto_20170818_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('comment', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='species',
            name='picture',
            field=models.ImageField(upload_to='species-images', verbose_name='Imagen'),
        ),
    ]
