# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodiversidad_app', '0002_auto_20170820_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=100, verbose_name='Ciudad')),
                ('interest', models.TextField(max_length=1000, verbose_name='Interes')),
                ('picture', models.ImageField(upload_to='species-images', verbose_name='Foto')),
                ('country', models.TextField(max_length=100, verbose_name='Pais')),
                ('fk_DjangoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='FavoriteSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_appuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biodiversidad_app.AppUser', verbose_name='IdUsuario')),
                ('fk_species_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biodiversidad_app.Species', verbose_name='IdEspecie')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
            },
        ),
    ]
