# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversidad_app', '0003_auto_20170819_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fk_species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biodiversidad_app.Species', verbose_name='Species'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1000, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email'),
        ),
    ]
